/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-1"
 * 	found in "../pkcs-1v2-1-modified.asn"
 */

#ifndef	_DigestInfo_H_
#define	_DigestInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PKCS1AlgorithmIdentifier.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DigestInfo */
typedef struct DigestInfo {
	PKCS1AlgorithmIdentifier_120P0_t	 digestAlgorithm;
	OCTET_STRING_t	 digest;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DigestInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DigestInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _DigestInfo_H_ */
#include <asn_internal.h>
