/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-1"
 * 	found in "../pkcs-1v2-1-modified.asn"
 */

#ifndef	_EncodingParameters_H_
#define	_EncodingParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncodingParameters */
typedef OCTET_STRING_t	 EncodingParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncodingParameters;
asn_struct_free_f EncodingParameters_free;
asn_struct_print_f EncodingParameters_print;
asn_constr_check_f EncodingParameters_constraint;
ber_type_decoder_f EncodingParameters_decode_ber;
der_type_encoder_f EncodingParameters_encode_der;
xer_type_decoder_f EncodingParameters_decode_xer;
xer_type_encoder_f EncodingParameters_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EncodingParameters_H_ */
#include <asn_internal.h>
