/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-1"
 * 	found in "../pkcs-1v2-1-modified.asn"
 */

#ifndef	_MaskGenAlgorithm_H_
#define	_MaskGenAlgorithm_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PKCS1AlgorithmIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MaskGenAlgorithm */
typedef PKCS1AlgorithmIdentifier_120P0_t	 MaskGenAlgorithm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaskGenAlgorithm;
asn_struct_free_f MaskGenAlgorithm_free;
asn_struct_print_f MaskGenAlgorithm_print;
asn_constr_check_f MaskGenAlgorithm_constraint;
ber_type_decoder_f MaskGenAlgorithm_decode_ber;
der_type_encoder_f MaskGenAlgorithm_encode_der;
xer_type_decoder_f MaskGenAlgorithm_decode_xer;
xer_type_encoder_f MaskGenAlgorithm_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MaskGenAlgorithm_H_ */
#include <asn_internal.h>
