/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-1"
 * 	found in "../pkcs-1v2-1-modified.asn"
 */

#ifndef	_PSourceAlgorithm_H_
#define	_PSourceAlgorithm_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PSourceAlgorithm */
typedef AlgorithmIdentifier_120P0_t	 PSourceAlgorithm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PSourceAlgorithm;
asn_struct_free_f PSourceAlgorithm_free;
asn_struct_print_f PSourceAlgorithm_print;
asn_constr_check_f PSourceAlgorithm_constraint;
ber_type_decoder_f PSourceAlgorithm_decode_ber;
der_type_encoder_f PSourceAlgorithm_encode_der;
xer_type_decoder_f PSourceAlgorithm_decode_xer;
xer_type_encoder_f PSourceAlgorithm_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PSourceAlgorithm_H_ */
#include <asn_internal.h>
