/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-1"
 * 	found in "../pkcs-1v2-1-modified.asn"
 */

#ifndef	_RSASSA_AlgorithmIdentifier_H_
#define	_RSASSA_AlgorithmIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RSASSA-AlgorithmIdentifier */
typedef AlgorithmIdentifier_120P0_t	 RSASSA_AlgorithmIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSASSA_AlgorithmIdentifier;
asn_struct_free_f RSASSA_AlgorithmIdentifier_free;
asn_struct_print_f RSASSA_AlgorithmIdentifier_print;
asn_constr_check_f RSASSA_AlgorithmIdentifier_constraint;
ber_type_decoder_f RSASSA_AlgorithmIdentifier_decode_ber;
der_type_encoder_f RSASSA_AlgorithmIdentifier_encode_der;
xer_type_decoder_f RSASSA_AlgorithmIdentifier_decode_xer;
xer_type_encoder_f RSASSA_AlgorithmIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RSASSA_AlgorithmIdentifier_H_ */
#include <asn_internal.h>
