/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-1"
 * 	found in "../pkcs-1v2-1-modified.asn"
 */

#ifndef	_SHA1Parameters_H_
#define	_SHA1Parameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SHA1Parameters */
typedef NULL_t	 SHA1Parameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SHA1Parameters;
asn_struct_free_f SHA1Parameters_free;
asn_struct_print_f SHA1Parameters_print;
asn_constr_check_f SHA1Parameters_constraint;
ber_type_decoder_f SHA1Parameters_decode_ber;
der_type_encoder_f SHA1Parameters_encode_der;
xer_type_decoder_f SHA1Parameters_decode_xer;
xer_type_encoder_f SHA1Parameters_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SHA1Parameters_H_ */
#include <asn_internal.h>
