/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-1"
 * 	found in "../pkcs-1v2-1-modified.asn"
 */

#ifndef	_TrailerField_H_
#define	_TrailerField_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TrailerField {
	TrailerField_trailerFieldBC	= 1
} e_TrailerField;

/* TrailerField */
typedef INTEGER_t	 TrailerField_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrailerField;
asn_struct_free_f TrailerField_free;
asn_struct_print_f TrailerField_print;
asn_constr_check_f TrailerField_constraint;
ber_type_decoder_f TrailerField_decode_ber;
der_type_encoder_f TrailerField_encode_der;
xer_type_decoder_f TrailerField_decode_xer;
xer_type_encoder_f TrailerField_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TrailerField_H_ */
#include <asn_internal.h>
